<a href="https://colab.research.google.com/github/satyam-jaat/NumPy-and-Pandas/blob/main/numpy_practice_questions_from_basic_to_advance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create 1D array having numbers from 0 to 9.

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. Create nxn identity matrix.

In [ ]:
import numpy as np

matrix = np.identity(3) #n=3
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


3. Create a n x m 2d array filled with zeros.

In [ ]:
import numpy as np

array = np.zeros((2,3)) #n=2, m=3
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


4. Create a n x m 2d array filled with random numbers.

In [ ]:
import numpy as np

array = np.random.rand(2,3) #n=2, m=3
print(array)

[[0.07446508 0.22626709 0.38381422]
 [0.42317672 0.40199556 0.86464504]]


5. Extract all odd numbers from an array.

In [ ]:
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])
odd_numbers = array[array % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


6. Replace all odd numbers from an array into -1.

In [ ]:
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])
array[array % 2 == 1] = -1
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. Find the shape(2d or 3d), size(length of array), and data type of given array.

In [ ]:
import numpy as np

array = np.array([[0,1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9,0]])
print("Shape", array.shape)
print("Size", array.size)
print("Data Type", array.dtype)

Shape (2, 10)
Size 20
Data Type int64


8. Reshape a 1d array of 12 elements into 3x4 matrix.


In [ ]:
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,])
array = array.reshape(3,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


9. Concatenate two 1d array into one.

In [ ]:
import numpy as np
array1 = np.array([1,5,3])
array2 = np.array([2,4,6])

array = np.concatenate((array1, array2))
print(array)

[1 5 3 2 4 6]


10. Find the sum of all elements in a 2D array.

In [ ]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
arr = np.sum(array)
print(arr)

21


11. Find the mean, median and standard deviation of 1D array.

In [ ]:
import numpy as np

array = np.array([6,2,3,4,5,6])
mean = np.mean(array)
median = np.median(array)
std = np.std(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)

Mean: 4.333333333333333
Median: 4.5
Standard Deviation: 1.4907119849998596


12. Multiply two matrix using numpy

In [ ]:
import numpy as np
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

product = np.dot(matrix1,matrix2)
print(product)

[[19 22]
 [43 50]]


13. Find the dot products of two vectors.

In [ ]:
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

dot_product = np.dot(v1,v2)
print(dot_product)


32


14. Compute the determinent of 2 x 2 matrix.


In [7]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

determinant = np.linalg.det(matrix)
print(determinant)

-2.0000000000000004


15. Find the inverse of 2 x 2 matrix.


In [10]:
import numpy as np

matrix = np.array([[1,2],[3,4]])

inverse = np.linalg.inv(matrix)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


16. Flatten a 2d array into 1d array

In [13]:
import numpy as np

array = np.array([[1,2],[3,4]])

arr = array.flatten()
print(arr)

[1 2 3 4]


17. Stack 2d array vertically and horizontally.

In [17]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

vertically_stack = np.vstack((arr1,arr2))
print(vertically_stack)
print("\n")
horizontally_stack = np.hstack((arr1,arr2))
print(horizontally_stack)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


18. Find the index of maximum and minimum value in array.

In [18]:
import numpy as np

arr = np.array([1,2,3,4,5,4])

max_index = np.argmax(arr)
min_index = np.argmin(arr)

print(max_index)
print(min_index)

4
0


19. Replace all NAN value of array with 0.

In [19]:
import numpy as np

arr = np.array([1,2,np.nan, 3, np.nan])

arr[np.isnan(arr)] = 0
print(arr)

[1. 2. 0. 3. 0.]


20. Normalize a 2d array (subtract the mean and divide by the standard deviation.)

In [20]:
import numpy as np

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std = np.std(arr)

normalized_arr = (arr-mean)/std
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


21. Solve a system of linear equations using NumPy.

In [28]:
import numpy as np

A = np.array([[2, 1], [1, 3]])
B = np.array([8, 13])

solution = np.linalg.solve(A, B)
print(solution)

[2.2 3.6]


22. Compute the eigenvalues and eigenvectors of a matrix.

In [32]:
import numpy as np

matrix = np.array([[4, 1], [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print(eigenvectors)

[5. 2.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


23. Perform element-wise operations on two arrays of different shapes using broadcasting.

In [34]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([2,3])

result = arr1+arr2
print(result)

[[3 5]
 [5 7]]


24. Find the unique elements and their counts in a 1D array.

In [37]:
import numpy as np

arr = np.array([1,2,3,2,5])
unique_elements,counts = np.unique(arr, return_counts=True)
print(unique_elements)
print(counts)

[1 2 3 5]
[1 2 1 1]


25.  Sort a 2D array by a specific column.

In [40]:
import numpy as np

arr = np.array([[1,2],[7,4],[2,6]])

sorted_arr = arr[arr[:,1].argsort()]
print(sorted_arr)


[[1 2]
 [7 4]
 [2 6]]


26. Find the indices of non-zero elements in a 1D array.

In [41]:
import numpy as np

arr = np.array([0, 1, 0, 2, 0, 3])

non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([1, 3, 5]),)


27. Create a 2D array with 1 on the border and 0 inside.

In [42]:
import numpy as np

arr = np.zeros((5, 5))

arr[0, :] = 1  # First row
arr[-1, :] = 1  # Last row
arr[:, 0] = 1  # First column
arr[:, -1] = 1  # Last column

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


28. Compute the outer product of two vectors.

In [43]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

outer_product = np.outer(vector1, vector2)
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


29. Find the correlation coefficient between two arrays.

In [44]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

correlation_coefficient = np.corrcoef(arr1, arr2)[0, 1]
print(correlation_coefficient)

-0.9999999999999999


30. Generate a random walk using NumPy.

In [56]:
import numpy as np

steps = 100
random_walk = np.cumsum(np.random.choice([-1, 1], size=steps))

print(random_walk)

[ 1  0 -1 -2 -1  0 -1  0  1  0  1  0  1  2  3  4  3  4  3  4  5  4  5  6
  7  8  7  6  7  6  7  8  9  8  7  8  9  8  7  6  5  6  5  6  5  6  7  6
  7  6  5  6  5  4  5  6  5  6  5  6  7  6  5  6  7  6  7  6  7  6  5  4
  5  4  3  2  1  0  1  2  1  0  1  2  3  2  1  2  3  2  3  4  3  2  3  4
  3  2  1  2]
